import { Stack, type StackProps, RemovalPolicy, Duration, Fn } from 'aws-cdk-lib';
import type { Construct } from 'constructs';
import { Bucket, BucketEncryption, BlockPublicAccess } from 'aws-cdk-lib/aws-s3';
import { PolicyStatement, Effect, AnyPrincipal, Role, ServicePrincipal } from 'aws-cdk-lib/aws-iam';
import { Port, type IVpc, type IGatewayVpcEndpoint, type SecurityGroup } from 'aws-cdk-lib/aws-ec2';
import { Secret, type ISecret } from 'aws-cdk-lib/aws-secretsmanager';
import {
  DatabaseProxy,
  ProxyTarget,
  type DatabaseInstance,
} from 'aws-cdk-lib/aws-rds';
import { KosRds } from '../constructs/kos-rds.js';
import { KosBastion } from '../constructs/kos-bastion.js';

export interface DataStackProps extends StackProps {
  vpc: IVpc;
  s3Endpoint: IGatewayVpcEndpoint;
}

/**
 * DataStack — RDS Postgres 16.5 + pgvector, S3 blobs bucket (VPCe-scoped),
 * and four Secrets Manager placeholders seeded out-of-band.
 *
 * Decisions enforced here:
 *  - D-03: `RemovalPolicy.RETAIN` on bucket + secrets (RDS retained inside
 *    KosRds). `cdk destroy` cannot touch stateful resources.
 *  - D-07: RDS sizing / engine version inside KosRds.
 *  - INF-07: Secrets Manager holds (placeholder) NOTION_TOKEN_KOS,
 *    AZURE_SEARCH_ADMIN_KEY, TELEGRAM_BOT_TOKEN, KOS_DASHBOARD_BEARER.
 *    Values are populated by `scripts/seed-secrets.sh` interactively after
 *    first deploy; threat T-01-SECRET-01 mitigation.
 *  - RESEARCH Pitfall 2: bucket policy uses `aws:SourceVpce` (NOT
 *    `aws:SourceIp`) so Lambda-in-VPC traffic through the S3 Gateway Endpoint
 *    is allowed; internet traffic and other VPCe traffic are denied.
 *
 * The bastion is gated behind CDK context `bastion=true` so it's provisioned
 * only for Task 3's schema-push window; redeploy without the flag destroys
 * it (threat T-01-BASTION-01 mitigation).
 */
export class DataStack extends Stack {
  public readonly rds: DatabaseInstance;
  public readonly rdsCredentialsSecret: ISecret;
  public readonly rdsSecurityGroup: SecurityGroup;
  public readonly rdsProxy: DatabaseProxy;
  public readonly rdsProxyEndpoint: string;
  /**
   * The Proxy "DbiResourceId" — the `prx-xxxxxxxx` identifier used in the
   * IAM `rds-db:connect` resource ARN. Extracted from the Proxy's ARN at
   * synth time (`arn:aws:rds:region:account:db-proxy:prx-xxxxxxxx`).
   */
  public readonly rdsProxyDbiResourceId: string;
  public readonly blobsBucket: Bucket;
  public readonly notionTokenSecret: Secret;
  public readonly azureSearchAdminSecret: Secret;
  public readonly telegramBotTokenSecret: Secret;
  public readonly dashboardBearerSecret: Secret;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    // --- RDS -----------------------------------------------------------------
    const rds = new KosRds(this, 'Rds', { vpc: props.vpc });
    this.rds = rds.instance;
    // KosRds uses `Credentials.fromGeneratedSecret`; `instance.secret` is
    // guaranteed to exist when credentials are generated by CDK.
    if (!rds.instance.secret) {
      throw new Error('KosRds instance did not expose a generated credentials secret');
    }
    this.rdsCredentialsSecret = rds.instance.secret;
    this.rdsSecurityGroup = rds.securityGroup;

    // --- RDS Proxy (Plan 04) -------------------------------------------------
    // T-01-PROXY-01: the Proxy enforces IAM auth; no password path is valid.
    // Lambdas outside the VPC reach the Proxy over its public endpoint, but
    // the only accepted credential is an IAM signed auth token (per
    // `rds-db:connect` on the Proxy's DbiResourceId). `allowFromAnyIpv4` is
    // accepted because egress IPs for out-of-VPC Lambdas are non-deterministic;
    // the alternative (putting the indexer in the VPC) would require a NAT
    // Gateway and violate D-05.
    const proxyRole = new Role(this, 'RdsProxyRole', {
      assumedBy: new ServicePrincipal('rds.amazonaws.com'),
    });
    this.rdsCredentialsSecret.grantRead(proxyRole);

    this.rdsProxy = new DatabaseProxy(this, 'RdsProxy', {
      proxyTarget: ProxyTarget.fromInstance(rds.instance),
      secrets: [this.rdsCredentialsSecret],
      vpc: props.vpc,
      iamAuth: true,
      requireTLS: true,
      role: proxyRole,
      securityGroups: [this.rdsSecurityGroup],
    });
    // Proxy ingress from anywhere — IAM auth is the gate (documented in SUMMARY).
    this.rdsProxy.connections.allowFromAnyIpv4(Port.tcp(5432));
    this.rdsProxyEndpoint = this.rdsProxy.endpoint;

    // Extract `prx-xxxxxxxx` from Proxy ARN at synth time:
    //   arn:aws:rds:<region>:<account>:db-proxy:prx-xxxxxxxx
    // Fn.select(6, Fn.split(':', arn)) → 'db-proxy:prx-xxxxxxxx'
    // Fn.select(1, Fn.split('/', ...))  → 'prx-xxxxxxxx'  (note ARN uses ':')
    // Simpler: final ARN segment starts with 'prx-', split on ':' index 6.
    const lastArnSegment = Fn.select(6, Fn.split(':', this.rdsProxy.dbProxyArn));
    // Segment format: 'db-proxy:prx-xxxxxxxx' is actually ONE ':'-delimited
    // pair; CDK's dbProxyArn places the prx-id as the final ':' segment:
    // 'arn:aws:rds:REGION:ACCT:db-proxy:prx-ID'. So index 6 = 'prx-ID'.
    this.rdsProxyDbiResourceId = lastArnSegment;

    // --- Blobs bucket --------------------------------------------------------
    // Audio + transcripts + documents share one bucket with key prefixes
    // (Phase 2+ agents write `audio/`, `transcripts/`, `docs/`).
    this.blobsBucket = new Bucket(this, 'Blobs', {
      // CDK auto-names to avoid global-name collisions.
      bucketName: undefined,
      encryption: BucketEncryption.S3_MANAGED,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      versioned: true,
      removalPolicy: RemovalPolicy.RETAIN,
      lifecycleRules: [{ abortIncompleteMultipartUploadAfter: Duration.days(7) }],
    });

    // Pitfall 2 mitigation: deny everything *except* traffic through the
    // S3 Gateway Endpoint. `aws:ViaAWSService=false` lets CloudFormation/AWS-
    // internal paths through during stack operations.
    this.blobsBucket.addToResourcePolicy(
      new PolicyStatement({
        sid: 'DenyAllExceptVpce',
        effect: Effect.DENY,
        principals: [new AnyPrincipal()],
        actions: ['s3:*'],
        resources: [this.blobsBucket.bucketArn, `${this.blobsBucket.bucketArn}/*`],
        conditions: {
          StringNotEquals: { 'aws:SourceVpce': props.s3Endpoint.vpcEndpointId },
          Bool: { 'aws:ViaAWSService': 'false' },
        },
      }),
    );

    // --- Secrets Manager placeholders ---------------------------------------
    // Values are seeded by scripts/seed-secrets.sh post-deploy; CDK creates
    // the entry shell only.
    const mkSecret = (constructId: string, name: string, description: string): Secret =>
      new Secret(this, constructId, {
        secretName: name,
        description,
        removalPolicy: RemovalPolicy.RETAIN,
      });

    this.notionTokenSecret = mkSecret(
      'NotionToken',
      'kos/notion-token',
      'Notion integration token (Kevin workspace)',
    );
    this.azureSearchAdminSecret = mkSecret(
      'AzureAdminKey',
      'kos/azure-search-admin',
      'Azure AI Search admin API key',
    );
    this.telegramBotTokenSecret = mkSecret(
      'TelegramBotToken',
      'kos/telegram-bot-token',
      'Telegram Bot API token (Phase 2 consumer; placeholder now)',
    );
    this.dashboardBearerSecret = mkSecret(
      'DashboardBearer',
      'kos/dashboard-bearer',
      'Static Bearer token for Next.js dashboard (Phase 3 consumer)',
    );

    // --- Bastion (opt-in via CDK context) -----------------------------------
    // Usage: `cdk deploy KosData --context bastion=true` provisions the
    // short-lived bastion for Task 3's schema push. A follow-up deploy without
    // the flag tears it down (T-01-BASTION-01 mitigation).
    const bastionFlag = this.node.tryGetContext('bastion');
    if (bastionFlag === 'true' || bastionFlag === true) {
      new KosBastion(this, 'Bastion', {
        vpc: props.vpc,
        rdsSecurityGroup: this.rdsSecurityGroup,
      });
    }
  }
}
