-- phase 8 outbound content + mutations + calendar + documents
-- Phase 8 Plan 08-00: Content drafts + publish authorizations + pending
-- mutations + document versions + calendar events cache.
-- See .planning/phases/08-outbound-content-calendar/08-00-PLAN.md.
--
-- Note on numbering: the original Plan 08-00 reserved 0015, but Phases
-- 4/5/6/7 + dashboard-roles migrations have since landed 0011..0019, so
-- the next available sequential number at execute time is 0020. References
-- in subsequent Plans (08-01..08-05) use 0020 verbatim.
--
-- Five tables, every one carrying owner_id uuid NOT NULL per D-13 (forward
-- compat for multi-tenant productisation per memory note
-- project_multi_tenant_future).
--
-- pgcrypto extension is assumed present (enabled in migration 0001 / Phase 1).

BEGIN;

-- content_drafts ---------------------------------------------------------
--
-- Source of truth for every per-platform draft generated by AGT-07. One
-- row per (topic_id, platform). Idempotency on (topic_id, platform) is
-- exploited by Step Functions Map state — replays of the same per-platform
-- worker invocation never double-insert.
--
-- `media_urls` is jsonb (not text[]) because some platforms (TikTok) carry
-- objects with caption/duration metadata, not bare strings.
-- `status` CHECK mirrors ContentDraftSchema's enum.
CREATE TABLE IF NOT EXISTS "content_drafts" (
  "id"             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id"       uuid        NOT NULL,
  "topic_id"       text        NOT NULL,
  "capture_id"     text        NOT NULL,
  "platform"       text        NOT NULL CHECK ("platform" IN ('instagram','linkedin','tiktok','reddit','newsletter')),
  "content"        text        NOT NULL,
  "media_urls"     jsonb       NOT NULL DEFAULT '[]'::jsonb,
  "status"         text        NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','edited','approved','skipped','scheduled','published','cancelled','failed')),
  "schedule_time"  timestamptz,
  "postiz_post_id" text,
  "created_at"     timestamptz NOT NULL DEFAULT now(),
  "approved_at"    timestamptz,
  "scheduled_at"   timestamptz,
  "published_at"   timestamptz,
  CONSTRAINT "content_drafts_topic_platform_uidx" UNIQUE ("topic_id", "platform")
);
CREATE INDEX IF NOT EXISTS "content_drafts_owner_status_idx"
  ON "content_drafts" ("owner_id", "status", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "content_drafts_owner_topic_idx"
  ON "content_drafts" ("owner_id", "topic_id");

-- content_publish_authorizations ----------------------------------------
--
-- Single-use token gating publisher's call to Postiz. dashboard-api Approve
-- route INSERTs; publisher SELECT-FOR-UPDATE, calls Postiz, UPDATEs
-- consumed_at + publish_result. Cascading delete on draft ensures no orphan
-- authorizations linger when a draft is hard-removed (rare; status='cancelled'
-- is the standard archive path).
CREATE TABLE IF NOT EXISTS "content_publish_authorizations" (
  "id"              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id"        uuid        NOT NULL,
  "draft_id"        uuid        NOT NULL REFERENCES "content_drafts"("id") ON DELETE CASCADE,
  "approved_by"     text        NOT NULL DEFAULT 'kevin',
  "approved_at"     timestamptz NOT NULL DEFAULT now(),
  "schedule_time"   timestamptz,
  "consumed_at"     timestamptz,
  "publish_result"  jsonb
);
CREATE INDEX IF NOT EXISTS "content_publish_authorizations_owner_draft_idx"
  ON "content_publish_authorizations" ("owner_id", "draft_id");

-- pending_mutations ------------------------------------------------------
--
-- AGT-08 proposer-side state. Every regex-prescreen + Haiku-confirmation +
-- Sonnet-resolution sequence that produces a non-zero confidence target
-- writes a row here. Dashboard reads WHERE status='proposed' to render
-- Approve cards. mutation-executor flips status to 'executed'/'failed' once
-- it acts on an approved row.
--
-- alternatives is jsonb (array of {target_ref, confidence}); empty by
-- default. The disambiguation list is bounded at 5 by the proposer.
CREATE TABLE IF NOT EXISTS "pending_mutations" (
  "id"              uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id"        uuid          NOT NULL,
  "capture_id"      text          NOT NULL,
  "mutation_type"   text          NOT NULL CHECK ("mutation_type" IN ('cancel_meeting','delete_task','archive_doc','cancel_content_draft','cancel_email_draft','reschedule_meeting')),
  "target_kind"     text          NOT NULL,
  "target_id"       text          NOT NULL,
  "target_display"  text          NOT NULL,
  "confidence"      numeric(4,3)  NOT NULL,
  "reasoning"       text,
  "alternatives"    jsonb         NOT NULL DEFAULT '[]'::jsonb,
  "status"          text          NOT NULL DEFAULT 'proposed' CHECK ("status" IN ('proposed','approved','executed','skipped','failed')),
  "proposed_at"     timestamptz   NOT NULL DEFAULT now(),
  "approved_at"     timestamptz,
  "executed_at"     timestamptz,
  "result"          text,
  "error"           text
);
CREATE INDEX IF NOT EXISTS "pending_mutations_owner_status_idx"
  ON "pending_mutations" ("owner_id", "status", "proposed_at" DESC);
CREATE INDEX IF NOT EXISTS "pending_mutations_capture_id_idx"
  ON "pending_mutations" ("capture_id");

-- document_versions ------------------------------------------------------
--
-- MEM-05 content-addressed document version chain. Inserted by
-- document-diff Lambda; sha256 is hash of EXTRACTED TEXT (not raw bytes)
-- so trivial re-saves don't produce phantom versions. UNIQUE (recipient_
-- email, doc_name, sha256) is the hard idempotency boundary.
CREATE TABLE IF NOT EXISTS "document_versions" (
  "id"               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id"         uuid        NOT NULL,
  "recipient_email"  text        NOT NULL,
  "doc_name"         text        NOT NULL,
  "sha256"           text        NOT NULL,
  "s3_bucket"        text        NOT NULL,
  "s3_key"           text        NOT NULL,
  "version_n"        integer     NOT NULL,
  "parent_sha256"    text,
  "diff_summary"     text,
  "sent_at"          timestamptz NOT NULL,
  "capture_id"       text        NOT NULL,
  CONSTRAINT "document_versions_recipient_doc_sha_uidx" UNIQUE ("recipient_email", "doc_name", "sha256")
);
CREATE INDEX IF NOT EXISTS "document_versions_recipient_doc_idx"
  ON "document_versions" ("recipient_email", "doc_name", "version_n" DESC);
CREATE INDEX IF NOT EXISTS "document_versions_owner_idx"
  ON "document_versions" ("owner_id", "sent_at" DESC);

-- calendar_events_cache --------------------------------------------------
--
-- MEM-05 read-only mirror of Google Calendar events. Composite PK
-- (event_id, account) lets the same event id collide across accounts
-- without conflict (rare but possible — same Google event id never collides
-- between Kevin's two accounts in practice, but the constraint future-proofs).
--
-- ignored_by_kevin is the cancel_meeting mutation flip target; partial
-- index on the false-side keeps the dashboard's hot read path tight.
CREATE TABLE IF NOT EXISTS "calendar_events_cache" (
  "event_id"          text        NOT NULL,
  "account"           text        NOT NULL CHECK ("account" IN ('kevin-elzarka','kevin-taleforge')),
  "owner_id"          uuid        NOT NULL,
  "calendar_id"       text        NOT NULL,
  "summary"           text        NOT NULL,
  "description"       text,
  "location"          text,
  "start_utc"         timestamptz NOT NULL,
  "end_utc"           timestamptz NOT NULL,
  "timezone"          text        NOT NULL DEFAULT 'Europe/Stockholm',
  "attendees_json"    jsonb       NOT NULL DEFAULT '[]'::jsonb,
  "is_all_day"        boolean     NOT NULL DEFAULT false,
  "ignored_by_kevin"  boolean     NOT NULL DEFAULT false,
  "updated_at"        timestamptz NOT NULL,
  "cached_at"         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("event_id", "account")
);
CREATE INDEX IF NOT EXISTS "calendar_events_cache_owner_window_idx"
  ON "calendar_events_cache" ("owner_id", "start_utc") WHERE "ignored_by_kevin" = false;
CREATE INDEX IF NOT EXISTS "calendar_events_cache_account_updated_idx"
  ON "calendar_events_cache" ("account", "updated_at" DESC);

COMMIT;

-- ROLLBACK (operator-run only):
-- BEGIN;
-- DROP TABLE IF EXISTS calendar_events_cache;
-- DROP TABLE IF EXISTS document_versions;
-- DROP TABLE IF EXISTS pending_mutations;
-- DROP TABLE IF EXISTS content_publish_authorizations;
-- DROP TABLE IF EXISTS content_drafts;
-- COMMIT;
